version: "3.9"  
services:
  app:
    container_name: app
    restart: always
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - ./data:/data/db
volumes:
  logvolume01: {}